services:
  fastapi:
    build:
      context: ./ai-recommendation
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env #.env가 루트에 있을때 기준
    restart: always

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
