spring:
  application:
    name: trendlog
#  profiles:
#    active: local
#  data:
#    redis:
#      host: localhost
#      port: 6379
##      password: (운영 배포용 시 주석 해제)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: your-super-secret-key-your-super-secret-key
  access-token-validity: 900000000   # 15분(0두개 붙임)
  refresh-token-validity: 604800000 # 7일
gcp:
  project-id: uida-3051b
  credentials:
    location: classpath:uida-3051b-c54f4eb20081.json
  bucket: trendlog-bucket
