spring:
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: redis
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 900000      # 15분
  refresh-token-validity: 604800000  # 7일

# GCP
gcp:
  project-id: ${GCP_PROJECT_ID}
  bucket: ${GCP_BUCKET}
  credentials:
    location: file:/secrets/gcp-service-key.json

# 외부 API
youtube:
  api:
    key: ${YOUTUBE_API_KEY}
    base-url: https://www.googleapis.com/youtube/v3

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY:}
